require('dotenv').config({ path: '../.env' })
const mongoose = require('mongoose')
const Article = require('../models/Article')
const PDFChunk = require('../models/PDFChunk')
const User = require('../models/User')

const GDPR_ARTICLES = [
  { articleNumber: 'Art.1', title: 'Subject-matter and objectives', chapter: 'Chapter I', keywords: ['objectives', 'regulation', 'fundamental rights'],
    content: 'This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. This Regulation protects fundamental rights and freedoms of natural persons and in particular their right to the protection of personal data.' },
  { articleNumber: 'Art.5', title: 'Principles relating to processing of personal data', chapter: 'Chapter II', keywords: ['principles', 'lawfulness', 'fairness', 'transparency', 'data minimisation', 'accuracy', 'storage limitation', 'integrity', 'confidentiality', 'accountability'],
    content: 'Personal data shall be: (a) processed lawfully, fairly and in a transparent manner in relation to the data subject (lawfulness, fairness and transparency); (b) collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes (purpose limitation); (c) adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed (data minimisation); (d) accurate and, where necessary, kept up to date (accuracy); (e) kept in a form which permits identification of data subjects for no longer than is necessary (storage limitation); (f) processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (integrity and confidentiality). The controller shall be responsible for, and be able to demonstrate compliance with, paragraph 1 (accountability).' },
  { articleNumber: 'Art.6', title: 'Lawfulness of processing', chapter: 'Chapter II', keywords: ['lawfulness', 'consent', 'contract', 'legal obligation', 'vital interests', 'public task', 'legitimate interests'],
    content: 'Processing shall be lawful only if and to the extent that at least one of the following applies: (a) the data subject has given consent to the processing of his or her personal data for one or more specific purposes; (b) processing is necessary for the performance of a contract to which the data subject is party; (c) processing is necessary for compliance with a legal obligation; (d) processing is necessary in order to protect the vital interests of the data subject; (e) processing is necessary for the performance of a task carried out in the public interest; (f) processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party.' },
  { articleNumber: 'Art.7', title: 'Conditions for consent', chapter: 'Chapter II', keywords: ['consent', 'conditions', 'withdrawal', 'freely given', 'specific', 'informed'],
    content: 'Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented to processing of his or her personal data. The request for consent shall be presented in a manner which is clearly distinguishable from the other matters, in an intelligible and easily accessible form, using clear and plain language. The data subject shall have the right to withdraw his or her consent at any time. The withdrawal of consent shall not affect the lawfulness of processing based on consent before its withdrawal.' },
  { articleNumber: 'Art.13', title: 'Information to be provided where personal data are collected from the data subject', chapter: 'Chapter III', keywords: ['transparency', 'information', 'data subject', 'collection', 'privacy notice'],
    content: 'Where personal data relating to a data subject are collected from the data subject, the controller shall, at the time when personal data are obtained, provide the data subject with information including: the identity and contact details of the controller; the contact details of the data protection officer; the purposes and legal basis for processing; the recipients of the personal data; the period for which data will be stored; the existence of data subject rights.' },
  { articleNumber: 'Art.17', title: 'Right to erasure (Right to be forgotten)', chapter: 'Chapter III', keywords: ['erasure', 'right to be forgotten', 'deletion', 'removal'],
    content: 'The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay where: the personal data are no longer necessary in relation to the purposes for which they were collected; the data subject withdraws consent; the data subject objects to the processing; the personal data have been unlawfully processed; the personal data have to be erased for compliance with a legal obligation.' },
  { articleNumber: 'Art.25', title: 'Data protection by design and by default', chapter: 'Chapter IV', keywords: ['privacy by design', 'privacy by default', 'data minimisation', 'pseudonymisation', 'technical measures'],
    content: 'Taking into account the state of the art, the cost of implementation and the nature, scope, context and purposes of processing as well as the risks of varying likelihood and severity for rights and freedoms of natural persons posed by the processing, the controller shall, both at the time of the determination of the means for processing and at the time of the processing itself, implement appropriate technical and organisational measures, such as pseudonymisation, which are designed to implement data-protection principles, such as data minimisation, in an effective manner and to integrate the necessary safeguards into the processing. The controller shall implement appropriate technical and organisational measures for ensuring that, by default, only personal data which are necessary for each specific purpose of the processing are processed.' },
  { articleNumber: 'Art.28', title: 'Processor', chapter: 'Chapter IV', keywords: ['processor', 'controller', 'data processing agreement', 'DPA', 'sub-processor'],
    content: 'Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures in such a manner that processing will meet the requirements of this Regulation and ensure the protection of the rights of the data subject. Processing by a processor shall be governed by a contract or other legal act under Union or Member State law, that is binding on the processor with regard to the controller.' },
  { articleNumber: 'Art.30', title: 'Records of processing activities', chapter: 'Chapter IV', keywords: ['ROPA', 'records', 'processing activities', 'documentation', 'accountability'],
    content: 'Each controller and, where applicable, the controller\'s representative, shall maintain a record of processing activities under its responsibility. That record shall contain all of the following information: the name and contact details of the controller; the purposes of the processing; a description of the categories of data subjects and categories of personal data; the categories of recipients; the transfers to third countries; the envisaged time limits for erasure; a general description of technical and organisational security measures.' },
  { articleNumber: 'Art.32', title: 'Security of processing', chapter: 'Chapter IV', keywords: ['security', 'encryption', 'pseudonymisation', 'confidentiality', 'integrity', 'availability', 'resilience', 'technical measures', 'organisational measures'],
    content: 'Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, the controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including as appropriate: (a) the pseudonymisation and encryption of personal data; (b) the ability to ensure the ongoing confidentiality, integrity, availability and resilience of processing systems and services; (c) the ability to restore the availability and access to personal data in a timely manner in the event of a physical or technical incident; (d) a process for regularly testing, assessing and evaluating the effectiveness of technical and organisational measures.' },
  { articleNumber: 'Art.33', title: 'Notification of a personal data breach to the supervisory authority', chapter: 'Chapter IV', keywords: ['breach notification', '72 hours', 'supervisory authority', 'incident', 'data breach'],
    content: 'In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority unless the personal data breach is unlikely to result in a risk to the rights and freedoms of natural persons. The notification shall at least: describe the nature of the personal data breach including where possible the categories and approximate number of data subjects concerned; communicate the name and contact details of the data protection officer; describe the likely consequences of the personal data breach; describe the measures taken or proposed to address the personal data breach.' },
  { articleNumber: 'Art.35', title: 'Data protection impact assessment', chapter: 'Chapter IV', keywords: ['DPIA', 'impact assessment', 'high risk', 'prior consultation', 'risk assessment'],
    content: 'Where a type of processing in particular using new technologies, and taking into account the nature, scope, context and purposes of the processing, is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall, prior to the processing, carry out an assessment of the impact of the envisaged processing operations on the protection of personal data. A single assessment may address a set of similar processing operations that present similar high risks. The controller shall seek the advice of the data protection officer, where designated, when carrying out a data protection impact assessment.' },
  { articleNumber: 'Art.37', title: 'Designation of the data protection officer', chapter: 'Chapter IV', keywords: ['DPO', 'data protection officer', 'designation', 'mandatory'],
    content: 'The controller and the processor shall designate a data protection officer in any case where: (a) the processing is carried out by a public authority or body; (b) the core activities of the controller or the processor consist of processing operations which require regular and systematic monitoring of data subjects on a large scale; or (c) the core activities of the controller or the processor consist of processing on a large scale of special categories of data.' },
  { articleNumber: 'Art.44', title: 'General principle for transfers', chapter: 'Chapter V', keywords: ['international transfer', 'third country', 'adequacy', 'safeguards'],
    content: 'Any transfer of personal data which are undergoing processing or are intended for processing after transfer to a third country or to an international organisation shall take place only if the conditions laid down in this Chapter are complied with by the controller and processor, including for onward transfers of personal data from the third country or an international organisation to another third country or to another international organisation.' },
  { articleNumber: 'Art.83', title: 'General conditions for imposing administrative fines', chapter: 'Chapter VIII', keywords: ['fines', 'penalties', 'sanctions', 'enforcement', '4% global turnover', '20 million euros'],
    content: 'Infringements of the following provisions shall be subject to administrative fines up to 20 000 000 EUR, or in the case of an undertaking, up to 4% of the total worldwide annual turnover of the preceding financial year, whichever is higher: the basic principles for processing, including conditions for consent; the data subjects rights; the transfers of personal data to a recipient in a third country. Each supervisory authority shall ensure that the imposition of administrative fines shall be effective, proportionate and dissuasive.' },
]

const PDF_CHUNKS = [
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 0, content: 'Zero Trust Architecture for Digital Hospitals: Zero Trust means "Never trust, always verify." Core components include: Identity verification before access, Continuous authentication, Device posture validation, Network micro-segmentation, Least privilege enforcement, Real-time risk scoring. Implementation Steps: 1. Centralized IAM deployment 2. Enforce MFA for all users 3. Segment medical devices from admin networks 4. Deploy conditional access policies 5. Monitor lateral movement.', metadata: { section: 'Zero Trust Architecture' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 1, content: 'STRIDE Threat Modeling Methodology: STRIDE stands for Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, and Elevation of Privilege. Example Threat - Ransomware Attack Path: 1. Phishing email 2. Credential theft 3. Privilege escalation 4. Lateral movement 5. Data encryption. Mitigation: MFA, Email security gateway, Network segmentation, Offline backups, SOC monitoring.', metadata: { section: 'Threat Modeling' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 2, content: 'Incident Response Lifecycle for Healthcare: 1. Detection - SIEM alerts, anomaly detection, EDR notifications 2. Containment - Isolate affected systems, block malicious IPs, disable compromised accounts 3. Eradication - Remove malware, patch vulnerabilities 4. Recovery - Restore from clean backups, validate system integrity 5. Post-incident review - Root cause analysis, lessons learned. GDPR requires: Notify authority within 72 hours, Inform affected individuals if high risk.', metadata: { section: 'Incident Response' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 3, content: 'Encryption Standards for Healthcare Data: AES-256 (Advanced Encryption Standard) for data at rest - all patient records, EHR data, diagnostic images must be encrypted using AES-256. TLS 1.3 (Transport Layer Security) for data in transit - all API communications, web traffic, and data transfers between hospital systems. Hardware Security Modules (HSM) for cryptographic key management. Encryption satisfies GDPR Article 32 requirements for appropriate technical measures.', metadata: { section: 'Encryption' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 4, content: 'Layered Security Architecture for Digital Hospital: Layer 1 – User Access Layer: Doctors, Nurses, Patients, Admin staff. Security: MFA, RBAC, Conditional access. Layer 2 – Application Layer: EHR, Billing, Telemedicine, AI diagnostic engines. Security: API Gateway, OAuth 2.0, OWASP Top 10. Layer 3 – Security Layer: IAM, SIEM, IDS/IPS, EDR. Layer 4 – Infrastructure: Cloud (AWS/Azure/GCP), On-prem, Backup. Security: AES-256 at rest, TLS 1.3 in transit, HSM, Immutable backups.', metadata: { section: 'Security Architecture' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 5, content: 'GDPR Key Articles for Hospitals - Regulatory Compliance: Article 5 – Data minimization, integrity, and confidentiality. Article 25 – Privacy by Design and Default. Article 30 – Record of Processing Activities (ROPA). Article 32 – Security of Processing (encryption, pseudonymization). Article 33 – 72-hour breach notification to supervisory authority. Article 35 – Data Protection Impact Assessment (DPIA). Hospitals must appoint: Data Protection Officer (DPO), Incident Response Lead, Security Governance Committee.', metadata: { section: 'GDPR Compliance' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 6, content: 'Identity and Access Management (IAM) for Healthcare: Role-Based Access Control (RBAC) ensures minimum privilege. Roles: Doctor (read/write patient records), Nurse (limited write access), Admin (system configuration), Patient (own records only). Multi-Factor Authentication (MFA) mandatory for all privileged accounts. Conditional access policies based on device health, location, and user risk. Privileged Identity Management (PIM) for admin accounts with just-in-time access.', metadata: { section: 'IAM and RBAC' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 7, content: 'Privacy by Design and Default (Article 25) Implementation: Technical measures: Data minimization in system design, Pseudonymization of patient identifiers, Encryption by default, Access controls built into architecture. Organizational measures: Privacy impact assessments before new systems, DPO involvement in system design, Staff training on data protection. Default settings: Only minimum necessary data collected, Strictest privacy settings as default, Opt-in rather than opt-out for non-essential processing.', metadata: { section: 'Privacy by Design' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 8, content: 'Cost Estimation Model for Hospital Cybersecurity (3-Year): IAM & MFA: Year 1 $150,000, Year 2-3 $40,000/year. SOC & SIEM: Year 1 $250,000, Year 2-3 $200,000/year. Encryption & HSM: Year 1 $120,000, Year 2-3 $30,000/year. Cloud Security: $200,000/year. Compliance & Audit: Year 1 $80,000, Year 2-3 $50,000/year. Estimated 3-Year Total: $1.8M – $2.5M depending on hospital size. Investment directly protects patient lives, data integrity, and institutional reputation.', metadata: { section: 'Cost Model' } },
  { documentName: 'GDPR_Cybersecurity_Hospital', chunkIndex: 9, content: 'Regional Compliance Mapping: Europe: GDPR + NIS2, mandatory DPO, annual compliance audit, EU data residency, DPIA before system changes. USA: HIPAA Security Rule (administrative, physical, technical safeguards), Business Associate Agreements (BAA), HITECH breach notification. Asia: India DPDP Act, Singapore PDPA, China PIPL - data localization, consent management, cross-border transfer approval. Africa: South Africa POPIA, Nigeria NDPR - cloud-first model, outsourced SOC (MSSP), secure remote access.', metadata: { section: 'Regional Compliance' } },
]

const seedArticles = async () => {
  await Article.deleteMany({})
  await Article.insertMany(GDPR_ARTICLES.map(a => ({ ...a, source: 'gdpr-website', isActive: true })))
  return { articlesSeeded: GDPR_ARTICLES.length }
}

const seedPDFChunks = async () => {
  await PDFChunk.deleteMany({ documentName: 'GDPR_Cybersecurity_Hospital' })
  await PDFChunk.insertMany(PDF_CHUNKS)
  return { chunksSeeded: PDF_CHUNKS.length }
}

const seedAdmin = async () => {
  const existing = await User.findOne({ email: 'admin@gdpr.ai' })
  if (!existing) {
    await User.create({ name: 'Admin', email: 'admin@gdpr.ai', password: 'Admin@1234', role: 'admin' })
    return { adminCreated: true }
  }
  return { adminCreated: false }
}

// Run if called directly
if (require.main === module) {
  mongoose.connect(process.env.MONGODB_URI)
    .then(async () => {
      console.log('Connected to MongoDB')
      const a = await seedArticles()
      const c = await seedPDFChunks()
      const u = await seedAdmin()
      console.log('Seeded:', { ...a, ...c, ...u })
      process.exit(0)
    })
    .catch(e => { console.error(e); process.exit(1) })
}

module.exports = { seedArticles, seedPDFChunks, seedAdmin }
